[package]
org = "isuruuy"
name = "practitioner"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "xyz"
name = "pdexplannet"
version = "0.0.1"
repository = "local"
